> **TODO**

**Try to Predict for Another Task**

Now, your are familiar with the simple pipeline of data mining. The final task for you is to explore the ```data/dataset.xlsx``` to predict one of the labels above:
* ```patient_addmited_to_regular_ward_(1=yes,_0=no)```
* ```patient_addmited_to_semi-intensive_unit_(1=yes,_0=no)```
* ```patient_addmited_to_intensive_care_unit_(1=yes,_0=no)```

> Requirements
* Use **Row 5001-5645** of ```data/dataset.xlsx``` as the Test Split. Write code or a jupyter notebook to show how you solve this task. Please give detailed comments of your code and a good demonstration of your results.

In [1]:
# Import necessary libraries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Take a glance at the provided data 

raw_data = pd.read_excel('data/dataset.xlsx', engine="openpyxl")

raw_data.info()
raw_data.describe()
raw_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5644 entries, 0 to 5643
Columns: 111 entries, Patient ID to ctO2 (arterial blood gas analysis)
dtypes: float64(70), int64(4), object(37)
memory usage: 4.8+ MB


Patient ID  Patient age quantile SARS-Cov-2 exam result  \
0  44477f75e8169d2                    13               negative   
1  126e9dd13932f68                    17               negative   
2  a46b4402a0e5696                     8               negative   
3  f7d619a94f97c45                     5               negative   
4  d9e41465789c2b5                    15               negative   

   Patient addmited to regular ward (1=yes, 0=no)  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Patient addmited to semi-intensive unit (1=yes, 0=no)  \
0                                                  0       
1                                                  0       
2                                                  0       
3                                                  0       
4                                                  0       

   Patient addmited to intensive care unit (1=yes, 0=no)  Hematocrit  \
0                                                  0             NaN   
1                                                  0        0.236515   
2                                                  0             NaN   
3                                                  0             NaN   
4                                                  0             NaN   

   Hemoglobin  Platelets  Mean platelet volume   ...  \
0         NaN        NaN                    NaN  ...   
1    -0.02234  -0.517413               0.010677  ...   
2         NaN        NaN                    NaN  ...   
3         NaN        NaN                    NaN  ...   
4         NaN        NaN                    NaN  ...   

   Hb saturation (arterial blood gases)  pCO2 (arterial blood gas analysis)  \
0                                   NaN                                 NaN   
1                                   NaN                                 NaN   
2                                   NaN                                 NaN   
3                                   NaN                                 NaN   
4                                   NaN                                 NaN   

   Base excess (arterial blood gas analysis)  \
0                                        NaN   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4                                        NaN   

   pH (arterial blood gas analysis)  Total CO2 (arterial blood gas analysis)  \
0                               NaN                                      NaN   
1                               NaN                                      NaN   
2                               NaN                                      NaN   
3                               NaN                                      NaN   
4                               NaN                                      NaN   

   HCO3 (arterial blood gas analysis)  pO2 (arterial blood gas analysis)  \
0                                 NaN                                NaN   
1                                 NaN                                NaN   
2                                 NaN                                NaN   
3                                 NaN                                NaN   
4                                 NaN                                NaN   

   Arteiral Fio2  Phosphor  ctO2 (arterial blood gas analysis)  
0            NaN       NaN                                 NaN  
1            NaN       NaN                                 NaN  
2            NaN       NaN                                 NaN  
3            NaN       NaN                                 NaN  
4            NaN       NaN                                 NaN  

[5 rows x 111 columns]

In [3]:
# Fill in missing features

raw_data.columns = [x.lower().strip().replace(' ','_') for x in raw_data.columns]

for x in raw_data.columns:
    if raw_data[x].dtype=='float16' or  raw_data[x].dtype=='float32' or  raw_data[x].dtype=='float64':
        # raw_data[x].fillna(raw_data[x].mean())
        raw_data[x].fillna(raw_data[x].mean(skipna=True), inplace=True)

raw_data = raw_data.fillna(-999)

# Convert label-typed features
for y in raw_data.columns:
    if raw_data[y].dtype=='object': 
        lbl = LabelEncoder()
        lbl.fit(list(raw_data[y].values))
        raw_data[y] = lbl.transform(list(raw_data[y].values))

raw_data.head(3)

patient_id  patient_age_quantile  sars-cov-2_exam_result  \
0        1588                    13                       0   
1         451                    17                       0   
2        3669                     8                       0   

   patient_addmited_to_regular_ward_(1=yes,_0=no)  \
0                                               0   
1                                               0   
2                                               0   

   patient_addmited_to_semi-intensive_unit_(1=yes,_0=no)  \
0                                                  0       
1                                                  0       
2                                                  0       

   patient_addmited_to_intensive_care_unit_(1=yes,_0=no)    hematocrit  \
0                                                  0     -2.186214e-09   
1                                                  0      2.365154e-01   
2                                                  0     -2.186214e-09   

     hemoglobin     platelets  mean_platelet_volume  ...  \
0 -1.601319e-08 -3.535004e-10          7.438142e-09  ...   
1 -2.234027e-02 -5.174130e-01          1.067657e-02  ...   
2 -1.601319e-08 -3.535004e-10          7.438142e-09  ...   

   hb_saturation_(arterial_blood_gases)  pco2_(arterial_blood_gas_analysis)  \
0                         -1.379737e-10                        8.416397e-09   
1                         -1.379737e-10                        8.416397e-09   
2                         -1.379737e-10                        8.416397e-09   

   base_excess_(arterial_blood_gas_analysis)  \
0                              -1.655685e-09   
1                              -1.655685e-09   
2                              -1.655685e-09   

   ph_(arterial_blood_gas_analysis)  total_co2_(arterial_blood_gas_analysis)  \
0                      4.139211e-10                            -7.472139e-09   
1                      4.139211e-10                            -7.472139e-09   
2                      4.139211e-10                            -7.472139e-09   

   hco3_(arterial_blood_gas_analysis)  po2_(arterial_blood_gas_analysis)  \
0                        6.070843e-09                      -2.469729e-08   
1                        6.070843e-09                      -2.469729e-08   
2                        6.070843e-09                      -2.469729e-08   

   arteiral_fio2      phosphor  cto2_(arterial_blood_gas_analysis)  
0   4.656613e-09  6.332993e-09                        5.243001e-09  
1   4.656613e-09  6.332993e-09                        5.243001e-09  
2   4.656613e-09  6.332993e-09                        5.243001e-09  

[3 rows x 111 columns]

In [17]:
# data preprocess

not_X_cols = ['patient_id','sars-cov-2_exam_result', 'patient_addmited_to_regular_ward_(1=yes,_0=no)', 'patient_addmited_to_semi-intensive_unit_(1=yes,_0=no)', 'patient_addmited_to_intensive_care_unit_(1=yes,_0=no)']
y_cols = ['patient_addmited_to_regular_ward_(1=yes,_0=no)']
X_cols = [x for x in raw_data.columns if x not in not_X_cols] # These columns are the features we can use to predict
X = raw_data[X_cols]
# Y_cols
y = raw_data[y_cols] 
# np.sum(Y.to_numpy(), axis=0)

In [6]:
# feature engineering(for X)

# from sklearn.preprocessing import 
X.head()

patient_age_quantile    hematocrit    hemoglobin     platelets  \
0                    13 -2.186214e-09 -1.601319e-08 -3.535004e-10   
1                    17  2.365154e-01 -2.234027e-02 -5.174130e-01   
2                     8 -2.186214e-09 -1.601319e-08 -3.535004e-10   
3                     5 -2.186214e-09 -1.601319e-08 -3.535004e-10   
4                    15 -2.186214e-09 -1.601319e-08 -3.535004e-10   

   mean_platelet_volume  red_blood_cells   lymphocytes  \
0          7.438142e-09     8.424447e-09 -7.866736e-09   
1          1.067657e-02     1.020042e-01  3.183658e-01   
2          7.438142e-09     8.424447e-09 -7.866736e-09   
3          7.438142e-09     8.424447e-09 -7.866736e-09   
4          7.438142e-09     8.424447e-09 -7.866736e-09   

   mean_corpuscular_hemoglobin_concentration (mchc)    leukocytes  \
0                                      1.014863e-09  6.215833e-09   
1                                     -9.507903e-01 -9.461035e-02   
2                                      1.014863e-09  6.215833e-09   
3                                      1.014863e-09  6.215833e-09   
4                                      1.014863e-09  6.215833e-09   

      basophils  ...  hb_saturation_(arterial_blood_gases)  \
0 -6.633739e-09  ...                         -1.379737e-10   
1 -2.237665e-01  ...                         -1.379737e-10   
2 -6.633739e-09  ...                         -1.379737e-10   
3 -6.633739e-09  ...                         -1.379737e-10   
4 -6.633739e-09  ...                         -1.379737e-10   

   pco2_(arterial_blood_gas_analysis)  \
0                        8.416397e-09   
1                        8.416397e-09   
2                        8.416397e-09   
3                        8.416397e-09   
4                        8.416397e-09   

   base_excess_(arterial_blood_gas_analysis)  \
0                              -1.655685e-09   
1                              -1.655685e-09   
2                              -1.655685e-09   
3                              -1.655685e-09   
4                              -1.655685e-09   

   ph_(arterial_blood_gas_analysis)  total_co2_(arterial_blood_gas_analysis)  \
0                      4.139211e-10                            -7.472139e-09   
1                      4.139211e-10                            -7.472139e-09   
2                      4.139211e-10                            -7.472139e-09   
3                      4.139211e-10                            -7.472139e-09   
4                      4.139211e-10                            -7.472139e-09   

   hco3_(arterial_blood_gas_analysis)  po2_(arterial_blood_gas_analysis)  \
0                        6.070843e-09                      -2.469729e-08   
1                        6.070843e-09                      -2.469729e-08   
2                        6.070843e-09                      -2.469729e-08   
3                        6.070843e-09                      -2.469729e-08   
4                        6.070843e-09                      -2.469729e-08   

   arteiral_fio2      phosphor  cto2_(arterial_blood_gas_analysis)  
0   4.656613e-09  6.332993e-09                        5.243001e-09  
1   4.656613e-09  6.332993e-09                        5.243001e-09  
2   4.656613e-09  6.332993e-09                        5.243001e-09  
3   4.656613e-09  6.332993e-09                        5.243001e-09  
4   4.656613e-09  6.332993e-09                        5.243001e-09  

[5 rows x 106 columns]

In [13]:
# view y
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5644 entries, 0 to 5643
Data columns (total 1 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   patient_addmited_to_regular_ward_(1=yes,_0=no)  5644 non-null   int64
dtypes: int64(1)
memory usage: 44.2 KB


In [14]:
# split dataset

X_train = X[0: 5000]
X_test = X[5000:-1]
y_train = y[0: 5000]
y_test = y[5000:-1]

In [ ]:
# view data

def plot_scatter(X,y,v_num, is_numpy=False):
    v_num = 1000
    if is_numpy == False:
        X = X.to_numpy()
        y = y.to_numpy()
    pos_slice = y[0:v_num]==1
    neg_slice = y[0:v_num]==0
    for i in np.arange(0, X.shape[1], 2):
        pos_x = X[0:v_num][pos_slice][:, i: i + 2]
        neg_x = X[0:v_num][neg_slice][:, i: i + 2]
        plt.figure(figsize=(6,10))
        plt.subplot(311)
        plt.scatter(pos_x[:,0],pos_x[:,1],marker='+', c='red')
        plt.scatter(neg_x[:,0],neg_x[:,1],marker='o', s = 2, c='lime')
        plt.xlabel(f'feature{i}')
        plt.ylabel(f'feature{i+1}')
        plt.savefig(f'figures/scatter/feature{i}and{i+1}.png')
        plt.show()

plot_scatter(X_train, y_train, 100, False)

In [15]:
# evaluate the model

from sklearn.metrics import confusion_matrix, f1_score, recall_score, precision_score, roc_curve, auc, make_scorer

def my_scoring(y_true, y_pred):
    # 正确率在0.7范围上寻找最高f1-score
    acc = sum(y_pred == y_true)/len(y_pred)
    ans = 0
    if acc > 0.5:
        ans = recall_score(y_true, y_pred)
    return ans

def cross_f1_score(model, X, y):
    sc = cross_val_score(model, X, y, scoring=make_scorer(my_scoring, greater_is_better=True))
    sc = sc.mean()
    print(sc)
    return sc

def tune_param(est, params):
    max_sc = 0
    best_param = {}
    for param in params:
        model = est(**param)
        sc = cross_f1_score(model, X_train, y_train)
        if sc  > max_sc:
            max_sc = sc
            best_param = param
    return best_param, max_sc

def evaluate_model(model, name, print_or_not:bool = True, need_fit = False):
    performance = {}
    
    # cv_acc = 0
    if name == 'K Nearest Neighbors' or name == 'Random Forest' or 'Decision Tree' or need_fit:
        model.fit(X_train, y_train)
        # print(cv_acc)
        # cv_acc = cv_acc.mean()
        # performance['cv_accuracy'] = cv_acc
    prds = model.predict(X_test)
    
    accuracy = accuracy_score(y_test, prds)
    performance['accuracy'] = accuracy
    
    conf_mat = confusion_matrix(y_test, prds)
    performance['confusion_matrix'] = conf_mat
    
    
    precision_sc = precision_score(y_test, prds)
    performance['precision_score'] = precision_sc
    
    
    recall_sc = recall_score(y_test, prds)
    performance['recall_score'] = recall_sc
    
    f1_sc = f1_score(y_test, prds)
    performance['f1_score'] = f1_sc
    
    if print_or_not == True:
        print(f'evaluation of {name}:')
        # print(f'Cross Validation\'s Accuracy of {name}: {cv_acc}')
        
        print(f'Accuracy of {name}: {accuracy}')
        print(f'Confussion Matrix of {name}:\n{conf_mat}')
        print(f"Precision score of {name}: {precision_sc}")
        print(f"Recall score of {name}: {recall_sc}")
        print(f"F1 score of {name}: {f1_sc}")
    
        if name != "Support Vector Machine":
            y_score = model.predict_proba(X_test)[:, 1]
            fpr, tpr, threshold = roc_curve(y_test, y_score)
            roc_auc = auc(fpr, tpr)
            plt.figure(figsize=(6,6))
            plt.title('Validation ROC')
            plt.plot(fpr, tpr, 'b', label = 'Val AUC = %0.3f' % roc_auc)
            plt.legend(loc = 'lower right')
            plt.plot([0, 1], [0, 1],'r--')
            plt.xlim([0, 1])
            plt.ylim([0, 1])
            plt.ylabel('True Positive Rate')
            plt.xlabel('False Positive Rate')
            plt.show()
            
    return performance


In [16]:
from sklearn.linear_model import LogisticRegression

LR_model = LogisticRegression(penalty='l2', C=1, class_weight={0:1, 1:20, 2:40, 3:30})

pf = evaluate_model(LR_model, "Logistic Regression")

ValueError: Class label 2 not present.

In [131]:
from sklearn.tree import DecisionTreeClassifier

DT_model = DecisionTreeClassifier(class_weight='balanced')
# DT_model = DecisionTreeClassifier(class_weight='balanced')

pf = evaluate_model(DT_model, 'Decision Tree')

evaluation of Decision Tree:
Accuracy of Decision Tree: 0.8989113530326595
Confussion Matrix of Decision Tree:
[[563  10   1   5]
 [ 19   7   1   2]
 [  8   2   2   3]
 [  7   3   4   6]]
Precision score of Decision Tree: 0.8989113530326595
Recall score of Decision Tree: 0.8989113530326595
F1 score of Decision Tree: 0.8989113530326595
